import { ReactNode } from "react";
import Head from "next/head";

import Footer from "./footer";
import Header from "./header";

type LayoutProps = {
  children: ReactNode;
};

const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>Connect Wallet</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-rows-3 grid-cols-12 h-screen bg-gray-300">
        <Header />
        <main className="col-span-12">{children}</main>
        <Footer />
      </div>
    </>
  );
};

export default Layout;
