import type { NextPage } from "next";
import Head from "next/head";

const Positive: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hmmmm</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen h-screen flex flex-col justify-center items-center p-4 bg-pink-500">
        <h2 className="text-[2rem] lg:text-[4rem] md:text-[4rem] font-extrabold text-gray-200">
          You're Gay
        </h2>
      </div>
    </>
  );
};

export default Positive;
