import type { NextPage } from "next";
import Head from "next/head";
import { ConnectButton } from "@rainbow-me/rainbowkit";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen h-screen flex flex-col justify-center items-center p-4 bg-gray-800">
        <h2 className="text-[2rem] lg:text-[4rem] md:text-[4rem] font-extrabold text-gray-300">
          Welcome to SubWallet Connect
        </h2>
        <div className="mt-7">
          <ConnectButton label="Select Wallet" />
        </div>
      </div>
    </>
  );
};

export default Home;
